### ISSUE TITLE
Bot stays looking at the chests.

### ISSUE THREAD

**Issue by barbarbar338** [PrismarineJS/mineflayer-collectblock#65]
When i say "collect dirt", bot stays looking at the chests like this: https://i.imgur.com/UkAyi4t.png
this is bot's inventory: https://i.imgur.com/hWk1IJt.png
and this is my console: https://i.imgur.com/sND3VwT.png

i changed plugin's code to see what's going on and this is the code
```js
// mineflayer-collectblock Inventory.js, line 67
function gotoChest(bot, location, cb) {
    console.log(location); // added this
    const pathfinder = bot.pathfinder;
    pathfinder.setGoal(new mineflayer_pathfinder_1.goals.GoalBlock(location.x, location.y, location.z));
    const events = new mineflayer_utils_1.TemporarySubscriber(bot);
    events.subscribeTo('goal_reached', () => {
        console.log("goal_reached"); // added this
        events.cleanup();
        cb();
    });
    events.subscribeTo('path_update', (results) => {
        console.log("path_update"); // added this -- spams this line to console
        if (results.status === 'noPath') {
            events.cleanup();
            cb(Util_1.error('NoPath', 'No path to target block!'));
        }
    });
    events.subscribeTo('goal_updated', () => {
        console.log("goal_updated"); // added this
        events.cleanup();
        cb(Util_1.error('PathfindingInterrupted', 'Pathfinding interrupted before item could be reached.'));
    });
}
```

my fetch chest code:
```ts
public fetchChests(bot: Bot, minecraft_data: IndexedData) {
        bot.collectBlock.chestLocations = bot.findBlocks({
	        matching: minecraft_data.blocksByName.chest.id,
	        maxDistance: 32,
	        count: 999999,
        });
        if (bot.collectBlock.chestLocations.length === 0) {
	        bot.chat(
		        `I don't see any chests nearby. You may need to assist me when my inventory is full. (or place some chests and use the "${CONFIG.PREFIX}chest" command.)`,
	        );
        } else
	        bot.chat(
		        `I see ${bot.collectBlock.chestLocations.length} chest(s) nearby. I'll use them when my inventory is full.`,
	        );
}
```

and my collect code:

```ts
	public collectBlock(bot: Bot, blockID: number, count?: number) {
		const limit = count || 1;
		return new Promise((resolve, reject) => {
			const blocks = bot.findBlocks({
				matching: blockID,
				maxDistance: 64,
				count: limit,
			});
			if (blocks.length < 1) {
				bot.chat("I don't see that block nearby.");
				resolve(false);
			} else {
				const targets = [];
				for (let i = 0; i < Math.min(blocks.length, limit); i++) {
					targets.push(bot.blockAt(blocks[i]));
				}
				bot.chat(
					`Found ${targets.length} block(s), starting to collect them.`,
				);
				bot.collectBlock.collect(targets, (err) => {
					if (err) {
						console.log(err);
						reject(err);
					} else resolve(true);
				});
			}
		});
	}
```

**Comment by SeanMcCord** [comment]
I had the same issue a few days ago. Right now there are a few issues with the chest interactions in collectblock. One is the goal type [GoalBlock](https://github.com/PrismarineJS/mineflayer-pathfinder/blob/1b8b3d70ea40b888d36a74954f72b25ab9dedbcb/lib/goals.js#L24) should be [GoalGetToBlock](https://github.com/PrismarineJS/mineflayer-pathfinder/blob/1b8b3d70ea40b888d36a74954f72b25ab9dedbcb/lib/goals.js#L106) as right now the bot is attempting to move to the position the chest occupies. I've [mentioned this in pr 53](https://github.com/PrismarineJS/mineflayer-collectblock/pull/53#discussion_r625509639) and I just made a focused pr for this issue #66 .
Additionally there are issues with the way collectblock attempts to place items into the chest. In my opinion the steps forward are
* merge pr #53 
* merge pr #63 
* merge pr #66 
* create new pr with fixes to chest interaction.

p.s. I appreciate you adding logging. Would you mind showing an example output. I'm assuming that the bot doesn't reach its goal and therefore does not log 'goal_reached'.

**Comment by barbarbar338** [comment]
it just spams "path_update" and does nothing (does not logs "goal_reached" or anything).  When I tell bot to come to me with another "pathfinding" command when it is stuck where it is, im getting "PathfindingInterrupted: Pathfinding interrupted before item could be reached." error as it should be: https://i.imgur.com/dJmiC9b.png

**Comment by SeanMcCord** [comment]
Thanks. If you change the goal in function gotoChest in mineflayer-collectblock/lib/Inventory.js from
```
pathfinder.setGoal(new mineflayer_pathfinder_1.goals.GoalBlock(location.x, location.y, location.z));
```
to
```
pathfinder.setGoal(new mineflayer_pathfinder_1.goals.GoalGetToBlock(location.x, location.y, location.z));
```

You should find that the bot does emit 'goal_reached' now; however, it fails to empty its inventory.
* [This line](https://github.com/PrismarineJS/mineflayer-collectblock/blob/a19cc0174c9b3634e792bc02156c66bead602a34/src/Inventory.ts#L124) seems to be problematic. I'm not sure what the correct way to check if the chest is full.
* Chest locations it has visited are not removed from the [candidate list](https://github.com/PrismarineJS/mineflayer-collectblock/blob/a19cc0174c9b3634e792bc02156c66bead602a34/src/Inventory.ts#L47).
* It [uses Bot#chestOpen()](https://github.com/PrismarineJS/mineflayer-collectblock/blob/a19cc0174c9b3634e792bc02156c66bead602a34/src/Inventory.ts#L119), but that is [deprecated](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botopenchestchestblock-or-minecartchestentity) in favor of [openContainer()](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botopencontainercontainerblock-or-containerentity).

**Comment by barbarbar338** [comment]
as you said, it opens chest but says "TypeError: chest.once is not a function" 
open chest: https://i.imgur.com/Xur7ioW.png
error and code: https://i.imgur.com/xndj7YR.png

API says "Returns a **promise** on a Container instance which represents the container you are opening.". Lemme see whats going on when use async await

**Comment by barbarbar338** [comment]
i changed [this line](https://github.com/PrismarineJS/mineflayer-collectblock/blob/a19cc0174c9b3634e792bc02156c66bead602a34/src/Inventory.ts#L124) with `(chest.items.length >= chest.inventoryStart)` and it stored one stack of items. but then gave "TypeError: Cannot read property 'type' of null": https://i.imgur.com/HuT5o9y.png - mineflayer/lib/plugins/inventory.js, line 223 (window.selectedItem comes "null")

**Comment by barbarbar338** [comment]
also changed `openChest` as `openContainer` and used promises, here is the result:

```js
// Inventory.js, line 87
function placeItems(bot, chestPos, itemFilter, cb) {
    const chestBlock = bot.blockAt(chestPos);
    if (chestBlock == null) {
        cb(Util_1.error('UnloadedChunk', 'Chest is in an unloaded chunk!'), true);
        return;
    }
    try {
        let itemsRemain = false;
        bot.openContainer(chestBlock).then(chest => {
            const tryDepositItem = (item, cb) => {
                // @ts-expect-error ; A workaround for checking if the chest is already full
                console.log(chest);
                if (chest.items().length >= chest.inventoryStart) {
                    // Mark that we have items that didn't fit.
                    itemsRemain = true;
                    cb();
                    return;
                }
                chest.deposit(item.type, item.metadata, item.count, cb);
            };
            const taskQueue = new mineflayer_utils_1.TaskQueue();
            for (const item of bot.inventory.items()) {
                if (itemFilter(item)) {
                    taskQueue.add(cb => tryDepositItem(item, cb));
                }
            }
            taskQueue.addSync(() => chest.close());
            taskQueue.runAll((err) => {
                if (err != null) {
                    cb(err, true);
                    return;
                }
                cb(undefined, itemsRemain);
            });
        })
    }
    catch (err) {
        // Sometimes open chest will throw a few asserts if block is not a chest
        cb(err, true);
    }
}
```

**Comment by barbarbar338** [comment]
well, I tried putting items into the chest with the command and realized that the error was caused by the Mineflayer. sometimes it puts the items and sometimes gives this error: https://i.imgur.com/9LXOPvk.png

i'll create an issue on mineflayer

**Comment by barbarbar338** [comment]
Once again I was wrong :D error was caused by the `mineflayer-web-inventory` plugin. I found [this](https://github.com/imharvol/mineflayer-web-inventory/issues/20) issue and removed `mineflayer-web-inventory` from my code and it worked :^)

i changed `pathfinder.setGoal(new mineflayer_pathfinder_1.goals.GoalBlock(location.x, location.y, location.z));` to `pathfinder.setGoal(new mineflayer_pathfinder_1.goals.GoalGetToBlock(location.x, location.y, location.z));` and placeItems to:
```js
function placeItems(bot, chestPos, itemFilter, cb) {
    const chestBlock = bot.blockAt(chestPos);
    if (chestBlock == null) {
        cb(Util_1.error('UnloadedChunk', 'Chest is in an unloaded chunk!'), true);
        return;
    }
    try {
        let itemsRemain = false;
        bot.openChest(chestBlock).then(chest => { // used promise
            const tryDepositItem = (item, cb) => {
                // @ts-expect-error ; A workaround for checking if the chest is already full
                if (chest.items().length >= chest.inventoryStart) { // removed window
                    // Mark that we have items that didn't fit.
                    itemsRemain = true;
                    cb();
                    return;
                }
                chest.deposit(item.type, item.metadata, item.count, cb);
            };
            const taskQueue = new mineflayer_utils_1.TaskQueue();
            for (const item of bot.inventory.items()) {
                if (itemFilter(item)) {
                    taskQueue.add(cb => tryDepositItem(item, cb));
                }
            }
            taskQueue.addSync(() => chest.close());
            taskQueue.runAll((err) => {
                if (err != null) {
                    cb(err, true);
                    return;
                }
                cb(undefined, itemsRemain);
            });
        });
    }
    catch (err) {
        // Sometimes open chest will throw a few asserts if block is not a chest
        cb(err, true);
    }
}
```
in `mineflayer-collectblock/lib/Inventory.js` and it works
