### ISSUE TITLE
[BUG?] Stuck mining “air”/“nothing”

### ISSUE THREAD

**Issue by ytcalifax** [PrismarineJS/mineflayer-collectblock#81]
I am developing a bot, that is supposed to find some diamond ore and mine it for me, however the bot often gets stuck swinging its pickaxe, but breaking no block (somewhat similar to what the bot does in #54). 

The code I used is basically as close as possible to what the example in the README.MD is. Is there a fix for this issue, or is there a workaround of some sort? 

Thanks in advance.

**Comment by Fus3n** [comment]
facing the same issue.

**Comment by SomeRandomGuy009** [comment]
> I am developing a bot, that is supposed to find some diamond ore and mine it for me, however the bot often gets stuck swinging its pickaxe, but breaking no block (somewhat similar to what the bot does in #54).
> 
> The code I used is basically as close as possible to what the example in the README.MD is. Is there a fix for this issue, or is there a workaround of some sort?
> 
> Thanks in advance.

facing the same issue, only for diamond tho, not for any other ore or block

**Comment by Cleboost** [comment]
![image](https://github.com/user-attachments/assets/4047dbed-4b51-45bd-88bc-25f5e0e16967)

#137
